name: "OpenWrt SDK"
description: "Build OpenWrt packages via the SDK"
author: aparcar
runs:
  using: 'composite'
  steps:
    - run: docker build --build-arg ARCH -t sdk $GITHUB_ACTION_PATH
      shell: bash
    - run: |
        docker run --rm \
          --env GITHUB_WORKSPACE \
          --env KEY_BUILD \
          --env PACKAGES \
          --env ARCH \
          --env CUSTOM_PKG_DIR\
          --env FEEDS_NEED_INSTALL \
          --env EXTRA_FEEDS \
          --env INDEX \
          --env SCRIPT_BEFORE_BUILD \
          --workdir /github/workspace \
          -v $(pwd):/github/workspace \
          -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
          sdk
      shell: bash
